function [ variableName ] = getVariableName( data )
data_fields = fieldnames(data);
for i = 1:length(data_fields)
    fieldname = data_fields{i};
    if      strcmp(fieldname,'plev') ||...
            strcmp(fieldname,'units') ||...
            strcmp(fieldname,'lat') ||...
            strcmp(fieldname,'latitude') ||...
            strcmp(fieldname,'lat_bnds') ||...
            strcmp(fieldname,'lat_bounds') ||...
            strcmp(fieldname,'lon') ||...
            strcmp(fieldname,'longitude') ||...
            strcmp(fieldname,'lon_bnds') ||...
            strcmp(fieldname,'lon_bounds') ||...
            strcmp(fieldname,'time') ||...
            strcmp(fieldname,'time_bnds') ||...
            strcmp(fieldname,'time_bounds')
                continue
    else
        variableName = fieldname;
        return
    end
end
end

